call pathogen#infect()
call pathogen#helptags()
syntax on
set mouse=a
set number
filetype plugin indent on
set background=dark
"colorscheme solarized
set laststatus=2
"source /usr/local/lib/python2.7/site-packages/powerline/bindings/vim/plugin/powerline.vim