#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
    # install homebrew if it's missing
    if ! command -v brew >/dev/null 2>&1; then
        echo "🍻 Installing homebrew"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    # update brew bundle
    if [ -f "$HOME/.config/brew/Brewfile" ]; then
        echo "📦 Updating homebrew bundle"
        brew bundle --file=$HOME/.config/brew/Brewfile
    fi
elif [ "$system_type" = "Linux" ]; then
    sudo apt-get update
    sudo apt-get install fish starship
fi

# if we have fish make it the default shell
if command -v fish >/dev/null 2>&1; then
    whiptail --yesno "Set the default shell to fish?" 8 50
    if [ $? -eq 0 ]; then
        echo "🐟 Configuring fish shell"
        echo `which fish` | sudo tee -a /etc/shells
        chsh -s `which fish`

        echo "🎣 Installing fisher and plugins"
        fish -c "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher"
        # install plugins
        fish -c "fisher update"
    fi
fi

# install volta
if ! command -v volta >/dev/null 2>&1; then
    whiptail --yesno "Install Volta?" 8 50
    if [ $? -eq 0 ]; then
        echo "⚡ Installing Volta"
        curl https://get.volta.sh | bash -s -- --skip-setup
    fi
fi

# vim
if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
