[username]
disabled = true

[aws]
symbol = "  "

[conda]
symbol = " "
disabled = true

[dart]
symbol = " "
disabled = true

[directory]
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "
disabled = true

[elm]
symbol = " "
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "
disabled = true

[hg_branch]
symbol = " "
disabled = true

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[memory_usage]
symbol = " "

[nim]
symbol = " "
disabled = true

[nix_shell]
symbol = " "

[nodejs]
disabled = true

[package]
symbol = " "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = " "
disabled = true

[scala]
symbol = " "
disabled = true

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "
disabled = true
